import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, readFileSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { randomUUID, createHmac } from 'node:crypto';
import { createApp, priceCart, verifySignature, validateProduct } from '../server.mjs';
import seed from '../seed.mjs';
import { MongoClient } from 'mongodb';
import { DatabaseSync } from 'node:sqlite';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';

test('prices come from the catalogue, quantities and availability are validated', () => {
  assert.equal(priceCart([{ id: 'tomatoes', quantity: 2, price: 1 }], seed, 4000, 49900).total, 13000);
  assert.equal(priceCart([{ id: 'honey', quantity: 3 }], seed, 4000, 49900).delivery, 0);
  for (const quantity of [-1, 0, 1.5, 51, '2']) assert.throws(() => priceCart([{ id: 'tomatoes', quantity }], seed, 0, 0));
  assert.throws(() => priceCart([{ id: 'tomatoes', quantity: 1 }, { id: 'tomatoes', quantity: 1 }], seed, 0, 0));
  assert.throws(() => priceCart([{ id: 'missing', quantity: 1 }], seed, 0, 0));
  assert.throws(() => priceCart([{ id: 'tomatoes', quantity: 1 }], seed.map(p => ({ ...p, available: false })), 0, 0));
});
test('product inputs cannot use script images or prices above MRP', () => {
  assert.equal(validateProduct(seed[0]).price, 4500);
  assert.throws(() => validateProduct({ ...seed[0], image: '/uploads/file.svg' }));
  assert.throws(() => validateProduct({ ...seed[0], price: 10000 }));
  assert.throws(() => validateProduct({ ...seed[0], available: 'true' }));
});
test('signature verification rejects malformed, tampered and unconfigured requests', () => {
  const signature = createHmac('sha256', 'secret').update('order|payment').digest('hex');
  assert.equal(verifySignature('order|payment', signature, 'secret'), true);
  assert.equal(verifySignature('other|payment', signature, 'secret'), false);
  assert.equal(verifySignature('order|payment', 'bad', 'secret'), false);
  assert.equal(verifySignature('order|payment', signature, ''), false);
});
test('SQLite importer preserves products, reviews, orders and fulfillment without overwriting on retry', { skip: !process.env.MONGODB_TEST_URI }, async t => {
  const dir=mkdtempSync(path.join(os.tmpdir(), 'health-partner-test-'));
  const source=path.join(dir,'store.sqlite');
  const sqlite=new DatabaseSync(source);
  sqlite.exec('CREATE TABLE products(body TEXT); CREATE TABLE orders(id TEXT,token TEXT,state TEXT,body TEXT,created INTEGER,gateway_id TEXT); CREATE TABLE reviews(id TEXT,product_id TEXT,name TEXT,rating INTEGER,comment TEXT,created INTEGER); CREATE TABLE order_fulfillment(order_id TEXT,status TEXT);');
  sqlite.prepare('INSERT INTO products VALUES (?)').run(JSON.stringify(seed[0]));
  sqlite.prepare('INSERT INTO orders VALUES (?,?,?,?,?,?)').run('old-order','old-token','paid',JSON.stringify({total:4500}),1,'order_old');
  sqlite.prepare('INSERT INTO reviews VALUES (?,?,?,?,?,?)').run('old-review',seed[0].id,'Customer',5,'Good',1);
  sqlite.prepare('INSERT INTO order_fulfillment VALUES (?,?)').run('old-order','delivered'); sqlite.close();
  const client=new MongoClient(process.env.MONGODB_TEST_URI); await client.connect();
  const database='hp_test_'+randomUUID().replaceAll('-',''), db=client.db(database);
  t.after(async()=>{await db.dropDatabase();await client.close(); if(path.dirname(dir)===path.resolve(os.tmpdir()) && path.basename(dir).startsWith('health-partner-test-')) rmSync(dir,{recursive:true});});
  const run=()=>new Promise((resolve,reject)=>{const child=spawn(process.execPath,[fileURLToPath(new URL('../migrate-sqlite.mjs',import.meta.url)),source],{env:{...process.env,MONGODB_URI:process.env.MONGODB_TEST_URI,MONGODB_DB:database},stdio:'pipe'});let output='';child.stderr.on('data',x=>output+=x);child.on('error',reject);child.on('exit',code=>code===0?resolve():reject(new Error(output)));});
  await run();
  assert.equal((await db.collection('orders').findOne({id:'old-order'})).fulfillment,'delivered');
  assert.equal((await db.collection('orders').findOne({id:'old-order'})).body.total,4500);
  assert.equal(await db.collection('reviews').countDocuments(),1);
  await db.collection('products').updateOne({id:seed[0].id},{$set:{name:'Updated in Mongo'}});
  await run();
  assert.equal(await db.collection('orders').countDocuments(),1);
  assert.equal((await db.collection('products').findOne({id:seed[0].id})).name,'Updated in Mongo');
});
test('HTTP flow: auth, CSRF, product uploads, persisted orders and verified payment lifecycle', { skip: !process.env.MONGODB_TEST_URI }, async t => {
  const dir = mkdtempSync(path.join(os.tmpdir(), 'health-partner-test-'));
  const env = { ADMIN_EMAIL: 'test@example.com', ADMIN_PASSWORD: 'a-test-password-123456', APP_ORIGIN: 'http://localhost:3000', DATA_DIR: path.join(dir, 'data'), UPLOADS_DIR: path.join(dir, 'uploads'), WHATSAPP_NUMBER: '919000000000', RAZORPAY_KEY_ID: 'rzp_test_dummy', RAZORPAY_KEY_SECRET: 'test-secret', RAZORPAY_WEBHOOK_SECRET: 'webhook-secret' };
  env.MONGODB_URI = process.env.MONGODB_TEST_URI;
  env.MONGODB_DB = 'hp_test_' + randomUUID().replaceAll('-', '');
  const cleanupClient = new MongoClient(env.MONGODB_URI); await cleanupClient.connect();
  t.after(async () => { await cleanupClient.db(env.MONGODB_DB).dropDatabase(); await cleanupClient.close(); });
  let server = await createApp(env); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  let base = `http://127.0.0.1:${server.address().port}`;
  let cookie = '';
  const originalFetch = globalThis.fetch; let remoteAmount, paymentStatus = 'authorized';
  globalThis.fetch = async (url, options) => {
    if (!String(url).startsWith('https://api.razorpay.com/')) return originalFetch(url, options);
    if (String(url).endsWith('/orders')) { remoteAmount = JSON.parse(options.body).amount; return Response.json({ id: 'order_test123' }); }
    const payment = { id: 'pay_test123', order_id: 'order_test123', amount: remoteAmount, currency: 'INR', status: paymentStatus };
    if (String(url).includes('/orders/')) return Response.json({ items: [payment] });
    return Response.json(payment);
  };
  t.after(async () => { globalThis.fetch = originalFetch; await new Promise(resolve => server.close(resolve)); if (path.dirname(dir) === path.resolve(os.tmpdir()) && path.basename(dir).startsWith('health-partner-test-')) rmSync(dir, { recursive: true }); });
  async function request(route, method = 'GET', data, headers = {}) {
    const response = await originalFetch(base + route, { method, headers: { Origin: env.APP_ORIGIN, Cookie: cookie, ...(data ? { 'Content-Type': 'application/json' } : {}), ...headers }, ...(data ? { body: JSON.stringify(data) } : {}) });
    return { status: response.status, body: await response.json(), response };
  }
  assert.equal((await request('/api/admin/orders')).status, 401);
  assert.equal((await request('/api/admin/orders/example/status', 'PUT', { status: 'delivered' })).status, 401);
  assert.equal((await request('/api/admin/login', 'POST', { email: env.ADMIN_EMAIL, password: env.ADMIN_PASSWORD }, { Origin: 'https://evil.example' })).status, 403);
  assert.equal((await request('/api/admin/login', 'POST', { email: env.ADMIN_EMAIL, password: 'wrong' })).status, 401);
  const login = await request('/api/admin/login', 'POST', { email: env.ADMIN_EMAIL, password: env.ADMIN_PASSWORD });
  assert.equal(login.status, 200); assert.match(login.response.headers.get('set-cookie'), /HttpOnly; SameSite=Strict/);
  cookie = login.response.headers.get('set-cookie').split(';')[0];
  const clip = Buffer.concat([Buffer.from('000000186674797069736f6d0000000069736f6d6d703432', 'hex'), Buffer.alloc(20)]);
  const videoUpload = await originalFetch(base + '/api/admin/upload', { method: 'POST', headers: { Cookie: cookie, Origin: env.APP_ORIGIN, 'Content-Type': 'video/mp4' }, body: clip });
  assert.equal(videoUpload.status, 201);
  const video = (await videoUpload.json()).url;
  const videoProduct = await request('/api/admin/products', 'POST', { ...seed[0], image: '', video });
  assert.equal(videoProduct.status, 201, 'video-only products supported');
  assert.equal((await request('/api/admin/products', 'POST', { ...seed[0], video: '/uploads/unsafe.html' })).status, 400);
  const range = await originalFetch(base + video, { headers: { Range: 'bytes=0-15' } });
  assert.equal(range.status, 206); assert.equal(range.headers.get('content-type'), 'video/mp4'); assert.equal((await range.arrayBuffer()).byteLength, 16);
  assert.equal((await originalFetch(base + video, { headers: { Range: 'bytes=9999-' } })).status, 416);
  assert.equal((await originalFetch(base + '/products/' + videoProduct.body.id)).status, 200);
  assert.equal((await originalFetch(base + '/products/missing')).status, 404);
  assert.equal((await request('/api/products/tomatoes/reviews')).body.count, 0);
  assert.equal((await request('/api/products/tomatoes/reviews', 'POST', { name: 'Customer', rating: 6, comment: 'Invalid rating' })).status, 400);
  const review = await request('/api/products/tomatoes/reviews', 'POST', { name: 'Customer', rating: 4, comment: 'Fresh and tasty.' });
  assert.equal(review.status, 201); assert.equal(review.body.average, 4); assert.equal(review.body.count, 1);
  const ratedProduct = (await request('/api/products')).body.find(p => p.id === 'tomatoes');
  assert.equal(ratedProduct.reviewCount, 1); assert.equal(ratedProduct.averageRating, 4);
  assert.equal(ratedProduct.latestReview.comment, 'Fresh and tasty.');
  const unratedProduct = (await request('/api/products')).body.find(p => p.id === 'honey');
  assert.equal(unratedProduct.reviewCount, 0); assert.equal(unratedProduct.latestReview, null);
  assert.equal((await request('/api/products/missing/reviews')).status, 404);
  const svg = await originalFetch(base + '/api/admin/upload', { method: 'POST', headers: { Cookie: cookie, Origin: env.APP_ORIGIN }, body: '<svg onload="alert(1)"></svg>' });
  assert.equal(svg.status, 400);
  const upload = await originalFetch(base + '/api/admin/upload', { method: 'POST', headers: { Cookie: cookie, Origin: env.APP_ORIGIN }, body: readFileSync(new URL('../public/images/tomatoes.jpg', import.meta.url)) });
  assert.equal(upload.status, 201); const { image } = await upload.json();
  const added = await request('/api/admin/products', 'POST', { ...seed[0], name: 'Test product', image }); assert.equal(added.status, 201);
  assert.equal((await originalFetch(base + image)).headers.get('content-type'), 'image/jpeg');
  assert.equal((await request(`/api/admin/products/${added.body.id}`, 'PUT', { ...added.body, price: 3000 })).status, 200);
  assert.equal((await request(`/api/admin/products/${added.body.id}`, 'DELETE')).status, 200);
  const orderInput = { token: randomUUID(), items: [{ id: 'tomatoes', quantity: 2, price: 1 }], customer: { name: 'Test customer', phone: '9000000000', address: 'Test address, 123456' }, method: 'whatsapp' };
  const wa = await request('/api/orders', 'POST', orderInput); assert.equal(wa.status, 201); assert.equal(wa.body.amount, 13000); assert.match(wa.body.whatsappUrl, /^https:\/\/wa.me\/919000000000\?text=/);
  assert.equal((await request('/api/orders', 'POST', orderInput)).body.id, wa.body.id);
  assert.equal((await request('/api/orders', 'POST', { ...orderInput, method: 'razorpay' })).status, 409, 'changing payment method cannot reuse an incompatible order');
  const paymentInput = { ...orderInput, method: 'razorpay', token: randomUUID() };
  const order = await request('/api/orders', 'POST', paymentInput); assert.equal(order.status, 201); assert.equal(remoteAmount, 13000);
  const verification = { id: order.body.id, token: paymentInput.token, razorpay_order_id: 'order_test123', razorpay_payment_id: 'pay_test123', razorpay_signature: 'bad' };
  assert.equal((await request('/api/payments/verify', 'POST', verification)).status, 400);
  verification.razorpay_signature = createHmac('sha256', env.RAZORPAY_KEY_SECRET).update('order_test123|pay_test123').digest('hex');
  assert.equal((await request('/api/payments/verify', 'POST', verification)).status, 409, 'authorized is not paid');
  const event = { event: 'payment.captured', payload: { payment: { entity: { id: 'pay_test123', order_id: 'order_test123', amount: 1, currency: 'INR', status: 'captured' } } } };
  async function webhook() { const raw = JSON.stringify(event); return originalFetch(base + '/api/payments/webhook', { method: 'POST', headers: { 'x-razorpay-signature': createHmac('sha256', env.RAZORPAY_WEBHOOK_SECRET).update(raw).digest('hex') }, body: raw }); }
  assert.equal((await webhook()).status, 409, 'wrong payment amount rejected');
  event.payload.payment.entity.amount = 13000;
  assert.equal((await webhook()).status, 200); assert.equal((await webhook()).status, 200, 'webhook retries are idempotent');
  assert.equal((await request('/api/payments/status', 'POST', { id: order.body.id, token: paymentInput.token })).body.state, 'paid');
  assert.equal((await request('/api/payments/status', 'POST', { id: order.body.id, token: 'wrong' })).status, 404);
  paymentStatus = 'captured'; assert.equal((await request('/api/payments/verify', 'POST', verification)).status, 200);
  assert.equal((await request('/api/admin/orders')).body.length, 2);
  assert.equal((await request('/api/admin/orders')).body.find(o => o.id === wa.body.id).fulfillment, 'in_process');
  for (const fulfillment of ['delivered', 'rejected', 'in_process', 'delivered']) {
    assert.equal((await request(`/api/admin/orders/${order.body.id}/status`, 'PUT', { status: fulfillment })).status, 200);
    const savedOrder = (await request('/api/admin/orders')).body.find(o => o.id === order.body.id);
    assert.equal(savedOrder.fulfillment, fulfillment); assert.equal(savedOrder.state, 'paid');
  }
  assert.equal((await request(`/api/admin/orders/${order.body.id}/status`, 'PUT', { status: 'unknown' })).status, 400);
  assert.equal((await request(`/api/admin/orders/${order.body.id}/status`, 'PUT', { status: 'rejected' }, { Origin: 'https://evil.example' })).status, 403);
  assert.equal((await request('/api/admin/orders/missing/status', 'PUT', { status: 'delivered' })).status, 404);
  assert.equal((await originalFetch(base + '/admin/orders')).status, 200);
  assert.equal((await originalFetch(base + '/.env')).status, 404);
  assert.equal((await originalFetch(base + '/data/store.sqlite')).status, 404);
  await new Promise(resolve => server.close(resolve)); server = await createApp(env); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); base = `http://127.0.0.1:${server.address().port}`;
  assert.equal((await request('/api/payments/status', 'POST', { id: order.body.id, token: paymentInput.token })).body.state, 'paid', 'orders persist after restart');
  assert.equal((await request('/api/admin/session')).status, 200, 'MongoDB sessions survive restart with unchanged credentials');
  const relogin = await request('/api/admin/login', 'POST', { email: env.ADMIN_EMAIL, password: env.ADMIN_PASSWORD });
  cookie = relogin.response.headers.get('set-cookie').split(';')[0];
  assert.equal((await request('/api/admin/orders')).body.find(o => o.id === order.body.id).fulfillment, 'delivered', 'fulfillment persists after restart');
});
